# -*- coding:utf-8 -*-
'''
@Author: nEwt0n_m1ku
@contact: cto@ddxnb.cn
@Time: 2024/06/13 0013 00:26
@version: 1.0
'''
# 国家代码和对应的中文名称字典
country_code_to_name = {
    'AF': '阿富汗', 'AX': '奥兰', 'AL': '阿尔巴尼亚', 'DZ': '阿尔及利亚', 'AS': '美属萨摩亚', 'AD': '安道尔',
    'AO': '安哥拉', 'AI': '安圭拉', 'AQ': '南极洲', 'AG': '安提瓜和巴布达', 'AR': '阿根廷', 'AM': '亚美尼亚',
    'AW': '阿鲁巴', 'AU': '澳大利亚', 'AT': '奥地利', 'AZ': '阿塞拜疆', 'BS': '巴哈马', 'BH': '巴林', 'BD': '孟加拉国',
    'BB': '巴巴多斯', 'BY': '白俄罗斯', 'BE': '比利时', 'BZ': '伯利兹', 'BJ': '贝宁', 'BM': '百慕大', 'BT': '不丹',
    'BO': '玻利维亚', 'BQ': '荷兰加勒比区', 'BA': '波黑', 'BW': '博茨瓦纳', 'BV': '布韦岛', 'BR': '巴西',
    'IO': '英属印度洋领地', 'BN': '文莱', 'BG': '保加利亚', 'BF': '布基纳法索', 'BI': '布隆迪', 'CV': '佛得角',
    'KH': '柬埔寨', 'CM': '喀麦隆', 'CA': '加拿大', 'KY': '开曼群岛', 'CF': '中非', 'TD': '乍得', 'CL': '智利',
    'CN': '中国', 'CX': '圣诞岛', 'CC': '科科斯（基林）群岛', 'CO': '哥伦比亚', 'KM': '科摩罗', 'CG': '刚果共和国',
    'CD': '刚果民主共和国', 'CK': '库克群岛', 'CR': '哥斯达黎加', 'CI': '科特迪瓦',
    'HR': '克罗地亚', 'CU': '古巴', 'CW': '库拉索', 'CY': '塞浦路斯', 'CZ': '捷克', 'DK': '丹麦', 'DJ': '吉布提',
    'DM': '多米尼克', 'DO': '多米尼加', 'EC': '厄瓜多尔', 'EG': '埃及', 'SV': '萨尔瓦多', 'GQ': '赤道几内亚',
    'ER': '厄立特里亚', 'EE': '爱沙尼亚', 'SZ': '斯威士兰', 'ET': '埃塞俄比亚', 'FK': '福克兰群岛', 'FO': '法罗群岛',
    'FJ': '斐济',
    'FI': '芬兰', 'FR': '法国', 'GF': '法属圭亚那', 'PF': '法属波利尼西亚', 'TF': '法属南部和南极领地', 'GA': '加蓬',
    'GM': '冈比亚',
    'GE': '格鲁吉亚', 'DE': '德国', 'GH': '加纳', 'GI': '直布罗陀', 'GR': '希腊', 'GL': '格陵兰', 'GD': '格林纳达',
    'GP': '瓜德罗普', 'GU': '关岛', 'GT': '危地马拉', 'GG': '根西', 'GN': '几内亚', 'GW': '几内亚比绍', 'GY': '圭亚那',
    'HT': '海地', 'HM': '赫德岛和麦克唐纳群岛', 'VA': '梵蒂冈', 'HN': '洪都拉斯', 'HK': '中国香港', 'HU': '匈牙利',
    'IS': '冰岛', 'IN': '印度', 'ID': '印度尼西亚', 'IR': '伊朗', 'IQ': '伊拉克', 'IE': '爱尔兰', 'IM': '马恩岛',
    'IL': '以色列', 'IT': '意大利', 'JM': '牙买加', 'JP': '日本', 'JE': '泽西', 'JO': '约旦', 'KZ': '哈萨克斯坦',
    'KE': '肯尼亚', 'KI': '基里巴斯', 'KP': '朝鲜', 'KR': '韩国', 'KW': '科威特', 'KG': '吉尔吉斯斯坦', 'LA': '老挝',
    'LV': '拉脱维亚', 'LB': '黎巴嫩', 'LS': '莱索托', 'LR': '利比里亚', 'LY': '利比亚', 'LI': '列支敦士登',
    'LT': '立陶宛',
    'LU': '卢森堡', 'MO': '中国澳门', 'MG': '马达加斯加', 'MW': '马拉维', 'MY': '马来西亚', 'MV': '马尔代夫',
    'ML': '马里',
    'MT': '马耳他', 'MH': '马绍尔群岛', 'MQ': '马提尼克', 'MR': '毛里塔尼亚', 'MU': '毛里求斯', 'YT': '马约特',
    'MX': '墨西哥',
    'FM': '密克罗尼西亚联邦', 'MD': '摩尔多瓦', 'MC': '摩纳哥', 'MN': '蒙古', 'ME': '黑山', 'MS': '蒙特塞拉特',
    'MA': '摩洛哥', 'MZ': '莫桑比克', 'MM': '缅甸', 'NR': '瑙鲁', 'NP': '尼泊尔', 'NL': '荷兰', 'NC': '新喀里多尼亚',
    'NZ': '新西兰', 'NI': '尼加拉瓜', 'NE': '尼日尔', 'NG': '尼日利亚', 'NU': '纽埃', 'NF': '诺福克岛',
    'MK': '北马其顿',
    'MP': '北马里亚纳群岛', 'NO': '挪威', 'OM': '阿曼', 'PK': '巴基斯坦', 'PW': '帕劳', 'PS': '巴勒斯坦',
    'PA': '巴拿马', 'PG': '巴布亚新几内亚', 'PY': '巴拉圭', 'PE': '秘鲁', 'PH': '菲律宾', 'PN': '皮特凯恩群岛',
    'PL': '波兰', 'PT': '葡萄牙', 'PR': '波多黎各', 'QA': '卡塔尔', 'RE': '留尼汪', 'RO': '罗马尼亚', 'RU': '俄罗斯',
    'RW': '卢旺达', 'BL': '圣巴泰勒米', 'SH': '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 'KN': '圣基茨和尼维斯',
    'LC': '圣卢西亚', 'MF': '法属圣马丁', 'PM': '圣皮埃尔和密克隆', 'VC': '圣文森特和格林纳丁斯', 'WS': '萨摩亚',
    'SM': '圣马力诺', 'ST': '圣多美和普林西比', 'SA': '沙特阿拉伯', 'SN': '塞内加尔', 'RS': '塞尔维亚', 'SC': '塞舌尔',
    'SL': '塞拉利昂', 'SG': '新加坡', 'SX': '荷属圣马丁', 'SK': '斯洛伐克', 'SI': '斯洛文尼亚', 'SB': '所罗门群岛',
    'SO': '索马里', 'ZA': '南非', 'GS': '南乔治亚和南桑威奇群岛', 'SS': '南苏丹', 'ES': '西班牙', 'LK': '斯里兰卡',
    'SD': '苏丹', 'SR': '苏里南', 'SJ': '斯瓦尔巴和扬马延', 'SE': '瑞典', 'CH': '瑞士', 'SY': '叙利亚',
    'TW': '中国台湾省', 'TJ': '塔吉克斯坦', 'TZ': '坦桑尼亚', 'TH': '泰国', 'TL': '东帝汶', 'TG': '多哥',
    'TK': '托克劳', 'TO': '汤加', 'TT': '特立尼达和多巴哥', 'TN': '突尼斯', 'TR': '土耳其', 'TM': '土库曼斯坦',
    'TC': '特克斯和凯科斯群岛', 'TV': '图瓦卢', 'UG': '乌干达', 'UA': '乌克兰', 'AE': '阿联酋', 'GB': '英国',
    'US': '美国', 'UM': '美国本土外小岛屿', 'UY': '乌拉圭', 'UZ': '乌兹别克斯坦', 'VU': '瓦努阿图', 'VE': '委内瑞拉',
    'VN': '越南', 'VG': '英属维尔京群岛', 'VI': '美属维尔京群岛', 'WF': '瓦利斯和富图纳', 'EH': '西撒哈拉',
    'YE': '也门', 'ZM': '赞比亚', 'ZW': '津巴布韦'}
province_to_pinyin = {
    "BeiJing": "北京",
    "BEIJING": "北京",
    "ShangHai": "上海",
    "SHANGHAI": "上海",
    "TianJin": "天津",
    "TIANJIN": "天津",
    "ChongQing": "重庆",
    "CHONGQING": "重庆",
    "XiangGang": "香港",
    "XIANGGANG": "香港",
    "AoMen": "澳门",
    "AOMEN": "澳门",
    "AnHui": "安徽",
    "ANHUI": "安徽",
    "FuJian": "福建",
    "FUJIAN": "福建",
    "GuangDong": "广东",
    "GUANGDONG": "广东",
    "GuangXi": "广西",
    "GUANGXI": "广西",
    "GuiZhou": "贵州",
    "GUIZHOU": "贵州",
    "GanSu": "甘肃",
    "GANSU": "甘肃",
    "HaiNan": "海南",
    "HAINAN": "海南",
    "HeBei": "河北",
    "HEBEI": "河北",
    "HeNan": "河南",
    "HENAN": "河南",
    "HeiLongJiang": "黑龙江",
    "HEILONGJIANG": "黑龙江",
    "HuBei": "湖北",
    "HUBEI": "湖北",
    "HuNan": "湖南",
    "HUNAN": "湖南",
    "JiLin": "吉林",
    "JILIN": "吉林",
    "JiangSu": "江苏",
    "JIANGSU": "江苏",
    "JiangXi": "江西",
    "JIANGXI": "江西",
    "LiaoNing": "辽宁",
    "LIAONING": "辽宁",
    "NeiMengGu": "内蒙古",
    "NEIMENGGU": "内蒙古",
    "NingXia": "宁夏",
    "NINGXIA": "宁夏",
    "QingHai": "青海",
    "QINGHAI": "青海",
    "ShaanXi": "陕西",
    "Shaanxi": "陕西",
    "SHAANXI": "陕西",
    "ShanXi": "山西",
    "SHANXI": "山西",
    "ShanDong": "山东",
    "SHANDONG": "山东",
    "SiChuan": "四川",
    "SICHUAN": "四川",
    "TaiWan": "台湾",
    "TAIWAN": "台湾",
    "XiZang": "西藏",
    "XIZANG": "西藏",
    "XinJiang": "新疆",
    "XINJIANG": "新疆",
    "YunNan": "云南",
    "YUNNAN": "云南",
    "ZheJiang": "浙江",
    "ZHEJIANG": "浙江"
}

city_to_pinyin = {
    "BeiJing": "北京",
    "ShangHai": "上海",
    "TianJin": "天津",
    "ChongQing": "重庆",
    "XiangGang": "香港",
    "AoMen": "澳门",
    "AnQing": "安庆",
    "BoZhou": "亳州",
    "BangBu": "蚌埠",
    "ChiZhou": "池州",
    "ChaoHu": "巢湖",
    "ChuZhou": "滁州",
    "FuYang": "阜阳",
    "HeFei": "合肥",
    "HuaiNan": "淮南",
    "HuaiBei": "淮北",
    "HuangShan": "黄山",
    "LiuAn": "六安",
    "MaAnShan": "马鞍山",
    "SuZhou": "宿州",
    "TongLing": "铜陵",
    "WuHu": "芜湖",
    "XuanCheng": "宣城",
    "FuZhou": "福州",
    "LongYan": "龙岩",
    "NanPing": "南平",
    "NingDe": "宁德",
    "PuTian": "莆田",
    "QuanZhou": "泉州",
    "SanXing": "三明",
    "XiaMen": "厦门",
    "ZhangZhou": "漳州",
    "ChaoZhou": "潮州",
    "DongGuan": "东莞",
    "FoShan": "佛山",
    "GuangZhou": "广州",
    "HeYuan": "河源",
    "HuiZhou": "惠州",
    "JiangMen": "江门",
    "JieYang": "揭阳",
    "MeiZhou": "梅州",
    "MaoMing": "茂名",
    "QingYuan": "清远",
    "ShenZhen": "深圳",
    "ShanTou": "汕头",
    "ShaoGuan": "韶关",
    "ShanWei": "汕尾",
    "YunFu": "云浮",
    "YangJiang": "阳江",
    "ZhuHai": "珠海",
    "ZhongShan": "中山",
    "ZhaoQing": "肇庆",
    "ZhanXiang": "湛江",
    "BeiHai": "北海",
    "BaiSe": "百色",
    "ChongZuo": "崇左",
    "GuiLi": "桂林",
    "GuiGang": "贵港",
    "HeZhou": "贺州",
    "HeChi": "河池",
    "LiuZhou": "柳州",
    "LaiBin": "来宾",
    "NanNing": "南宁",
    "QinZhou": "钦州",
    "WuZhou": "梧州",
    "YuLin": "玉林",
    "AnShun": "安顺",
    "GuiYang": "贵阳",
    "LiuPanShui": "六盘水",
    "BaiYin": "白银",
    "JinChang": "金昌",
    "JiaYuGuan": "嘉峪关",
    "JiuQuan": "酒泉",
    "LanZhou": "兰州",
    "QingYang": "庆阳",
    "TianShui": "天水",
    "WuWei": "武威",
    "ZhangYe": "张掖",
    "HaiKou": "海口",
    "SanYa": "三亚",
    "BaoDing": "保定",
    "ChengDe": "承德",
    "CangZhou": "沧州",
    "HanDan": "邯郸",
    "HengShui": "衡水",
    "LangFang": "廊坊",
    "QinHuangDao": "秦皇岛",
    "ShiJiaZhuang": "石家庄",
    "TangShan": "唐山",
    "XingTai": "邢台",
    "ZhangJiaKou": "张家口",
    "AnYang": "安阳",
    "JiaoZuo": "焦作",
    "KaiFeng": "开封",
    "LuoYang": "洛阳",
    "HeBi": "鹤壁",
    "LuoHe": "漯河",
    "NanYang": "南阳",
    "PingDingShan": "平顶山",
    "PuYang": "濮阳",
    "SanMenXia": "三门峡",
    "SHangQiu": "商丘",
    "XinXiang": "新乡",
    "XuChang": "许昌",
    "XinYang": "信阳",
    "ZhengZhou": "郑州",
    "ZhouKou": "周口",
    "ZhuMaDian": "驻马店",
    "DaQing": "大庆",
    "HaErBin": "哈尔滨",
    "HeGang": "鹤岗",
    "HeiHe": "黑河",
    "JiXi": "鸡西",
    "JiaMuSi": "佳木斯",
    "MuDanJiang": "牡丹江",
    "QiQiHaEr": "齐齐哈尔",
    "QiTaiHe": "七台河",
    "SuiHua": "绥化",
    "ShuangYaShan": "双鸭山",
    "YiChun": "伊春",
    "E'Zhou": "鄂州",
    "HuangShi": "黄石",
    "HuangGang": "黄冈",
    "JingZhou": "荆州",
    "JingMen": "荆门",
    "ShiYan": "十堰",
    "WuHan": "武汉",
    "XiangYang": "襄阳",
    "XiaoGan": "孝感",
    "XianNing": "咸宁",
    "YiChang": "宜昌",
    "ChangSha": "长沙",
    "ChangDe": "常德",
    "ChenZhou": "郴州",
    "HengYang": "衡阳",
    "HuaiHua": "怀化",
    "LouDi": "娄底",
    "ShaoYang": "邵阳",
    "XiangTan": "湘潭",
    "YueYang": "岳阳",
    "YiYang": "益阳",
    "YongZhou": "永州",
    "ZhuZhou": "株洲",
    "ZhangJiaJie": "张家界",
    "BaiShan": "白山",
    "BaiCheng": "白城",
    "ChangChun": "长春",
    "JiLin": "吉林",
    "LiaoYuan": "辽源",
    "SiPing": "四平",
    "SongYuan": "松原",
    "TongHua": "通化",
    "ChangZhou": "常州",
    "HuaiAn": "淮安",
    "LianYunGang": "连云港",
    "NanJing": "南京",
    "NanTong": "南通",
    "SuZhou": "苏州",
    "SuQian": "宿迁",
    "TaiZhou": "泰州",
    "WuXi": "无锡",
    "XuZhou": "徐州",
    "YanCheng": "盐城",
    "YangZhou": "扬州",
    "ZhenJiang": "镇江",
    "FuZhou": "抚州",
    "GanZhou": "赣州",
    "JingDeZhen": "景德镇",
    "JiuJiang": "九江",
    "JiAn": "吉安",
    "NanChang": "南昌",
    "PingXiang": "萍乡",
    "ShangRao": "上饶",
    "XinYu": "新余",
    "YingTan": "鹰潭",
    "AnShan": "鞍山",
    "BenXi": "本溪",
    "ChaoYang": "朝阳",
    "DaLian": "大连",
    "DanDong": "丹东",
    "FuShun": "抚顺",
    "FuXin": "阜新",
    "HuLuDao": "葫芦岛",
    "JinZhou": "锦州",
    "LiaoYang": "辽阳",
    "PanJin": "盘锦",
    "ShenYang": "沈阳",
    "TieLing": "铁岭",
    "YingKou": "营口",
    "BaoTou": "包头",
    "ChiFeng": "赤峰",
    "E'ErDuoSi": "鄂尔多斯",
    "HuHeHaoTe": "呼和浩特",
    "TongLiao": "通辽",
    "WuHai": "乌海",
    "GuYuan": "固原",
    "WuZhong": "吴忠",
    "YingChuan": "银川",
    "XiNing": "西宁",
    "AnKang": "安康",
    "BaoJi": "宝鸡",
    "HanZhong": "汉中",
    "ShangLuo": "商洛",
    "TongChuan": "铜川",
    "WeiNan": "渭南",
    "Xi'an": "西安",
    "Xi’an": "西安",
    "YaNan": "延安",
    "XianYang": "咸阳",
    "YuLin": "榆林",
    "ChangZhi": "长治",
    "DaTong": "大同",
    "JinCheng": "晋城",
    "LinFen": "临汾",
    "ShuoZhou": "朔州",
    "TaiYuan": "太原",
    "XinZhou": "忻州",
    "YangQuan": "阳泉",
    "YunCheng": "运城",
    "BinZhou": "滨州",
    "DongYing": "东营",
    "DeZhou": "德州",
    "HeZe": "菏泽",
    "JiNan": "济南",
    "JiNing": "济宁",
    "LaiWu": "莱芜",
    "LinYi": "临沂",
    "LiaoCheng": "聊城",
    "QingDao": "青岛",
    "RiZhao": "日照",
    "TaiAn": "泰安",
    "WeiFang": "潍坊",
    "WeiHai": "威海",
    "YanTai": "烟台",
    "ZiBo": "淄博",
    "ZaoZhuang": "枣庄",
    "BaZhong": "巴中",
    "ChengDu": "成都",
    "DeYang": "德阳",
    "DaZhou": "达州",
    "GuangYuan": "广元",
    "GuangAn": "广安",
    "LuZhou": "泸州",
    "LeShan": "乐山",
    "MianYang": "绵阳",
    "MeiShan": "眉山",
    "NeiJiang": "内江",
    "NanChong": "南充",
    "PanZhiHua": "攀枝花",
    "SuiNing": "遂宁",
    "YaAn": "雅安",
    "YiBin": "宜宾",
    "ZiGong": "自贡",
    "Ziyang": "资阳",
    "GaoXiong": "高雄",
    "JiLong": "基隆",
    "JiaYi": "嘉义",
    "TaiBei": "台北",
    "TaiZhong": "台中",
    "XinZhu": "新竹",
    "LaSa": "拉萨",
    "KeLaMaYi": "克拉玛依",
    "WuLuMuQi": "乌鲁木齐",
    "BaoShan": "保山",
    "KunMing": "昆明",
    "YuXi": "玉溪",
    "ZhaoTong": "昭通",
    "HangZhou": "杭州",
    "HuZhou": "湖州",
    "JiaXing": "嘉兴",
    "JinHua": "金华",
    "LiShui": "丽水",
    "NingBo": "宁波",
    "QuZhou": "衢州",
    "ShaoXing": "绍兴",
    "TaiZhou": "台州",
    "WenZhou": "温州",
    "ZhouShan": "舟山"
}
ISP_to_ch={
    # "chinatelecom": "中国电信",
    "CHINATELECOM": "中国电信",
    "CHINANET": "中国电信",
    "CHINA": "中国",
    "UNICOM": "联通",
    "PROVINCE": "省级",
    "NETWORK": "网络",
}
net_type={
    "ISP": "运营商",
    "EDUCATION": "教育",
    "BUSINESS": "企业",
    "HOSTING": "托管"
}
# 合并字典
net_dict = {}
net_dict.update(province_to_pinyin)
net_dict.update(ISP_to_ch)
def translate_city_names(input_str):
    parts = input_str.split()
    translated_parts = [net_dict.get(part.upper(), part) for part in parts]
    return " ".join(translated_parts)

